[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.(py|pyi)$"
exclude = "(\\.git|\\.venv|build|dist|__pycache__)"

[tool.isort]
profile = "black"
line_length = 100
known_first_party = []
skip = ["build", "dist", "__pycache__"]